import {beforeAll,expect,it} from 'vitest';
import fs from 'node:fs';import path from 'node:path';import {loadPyodide} from 'pyodide';
let py:any;const web=process.cwd();
async function call(action:string,payload:Record<string,unknown>={}){py.globals.set('request_json',JSON.stringify({action,...payload}));const raw=await py.runPythonAsync('bridge.handle_json(request_json)');py.globals.delete('request_json');return JSON.parse(String(raw));}
beforeAll(async()=>{py=await loadPyodide();py.FS.mkdirTree('/demo/ledgerly');for(const n of ['__init__.py','agent.py','extract.py','paypal.py'])py.FS.writeFile('/demo/ledgerly/'+n,fs.readFileSync(path.join(web,'public','python','ledgerly',n),'utf8'));py.FS.writeFile('/demo/bridge.py',fs.readFileSync(path.join(web,'public','python','bridge.py'),'utf8'));await py.runPythonAsync("import sys; sys.path.insert(0, '/demo'); import bridge");});
it('runs the actual Python invoice workflow through approval, signed webhook and overdue reminder',async()=>{
 await call('reset');const email=fs.readFileSync(path.join(web,'public','fixtures','01_simple_usd_hourly.txt'),'utf8');const analysis=await call('analyze',{text:email});expect(analysis.result.confidence).toBeGreaterThan(0.5);expect(analysis.result.line_items.length).toBeGreaterThan(0);
 const draft=await call('draft',{text:email});expect(draft.result.unauthorized_send_blocked).toBe(true);expect(draft.state.mock_requests).toBe(3);const invoice=draft.state.ledger[0].invoice_id;const send=draft.state.pending.find((x:any)=>x.kind==='send_invoice');expect(send).toBeTruthy();
 const sent=await call('approve',{action_id:send.id});expect(sent.state.ledger[0].status).toBe('SENT');const due=new Date(`${sent.state.ledger[0].due_on}T00:00:00Z`);due.setUTCDate(due.getUTCDate()+1); const overdue=due.toISOString().slice(0,10);const payment=await call('payment',{invoice_id:invoice,amount:'100'});expect(payment.state.ledger[0].status).toBe('PARTIALLY_PAID');expect((await call('replay')).result.duplicate).toBe(true);
 await call('advance',{day:overdue});const chase=await call('chase');const reminder=chase.state.pending.find((x:any)=>x.kind==='send_reminder');expect(reminder).toBeTruthy();const approved=await call('approve',{action_id:reminder.id});expect(approved.state.ledger[0].reminders_sent).toBe(1);expect(approved.state.external_calls).toBe(0);
});
it('keeps draft sends blocked until the visitor approves or rejects the action',async()=>{await call('reset');const email=fs.readFileSync(path.join(web,'public','fixtures','01_simple_usd_hourly.txt'),'utf8');const draft=await call('draft',{text:email});expect(draft.state.ledger[0].status).toBe('DRAFT');expect(draft.result.unauthorized_send_blocked).toBe(true);expect(draft.state.mock_requests).toBe(3);const item=draft.state.pending.find((x:any)=>x.kind==='send_invoice');const rejected=await call('reject',{action_id:item.id});expect(rejected.state.ledger[0].status).toBe('DRAFT');expect(rejected.state.mock_requests).toBe(3);});