import './style.css';
import {WorkerClient, WorkerUnavailableError} from './worker-client';
const $=<T extends HTMLElement>(selector:string)=>document.querySelector(selector) as T;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const worker=new WorkerClient(()=>new Worker(new URL('./engine.worker.ts',import.meta.url),{type:'module'}),{
 ready:()=>status('Python loaded locally. No external service is connected.','ready'),
 unavailable:engineUnavailable,
});
let ready=false,busy=false,analysisResult:any=null,needsFreshSandbox=false;
function status(text:string,kind='info'){$<HTMLElement>('#status-message').textContent=text;$<HTMLElement>('#status-message').dataset.kind=kind;}
function call(action:string,payload:Record<string,unknown>={}){return worker.call(action,payload);}
function recoveryMessage(error:WorkerUnavailableError){return `${error.message} The in-memory sandbox is unavailable. Restart opens an empty sandbox. Your source email is still here; no action will be replayed.`;}
function engineUnavailable(error:WorkerUnavailableError){
 needsFreshSandbox=true;analysisResult=null;setControls(false);
 document.querySelectorAll<HTMLButtonElement>('#approval-list button,#ledger-list button,#draft,#replay-webhook').forEach(button=>button.disabled=true);
 for(const id of ['approval-list','ledger-list'])$<HTMLElement>(`#${id}`).setAttribute('aria-disabled','true');
 const start=$<HTMLButtonElement>('#engine-start');start.disabled=false;start.textContent='Restart empty sandbox';
 $<HTMLElement>('#engine-status').textContent='PYTHON UNAVAILABLE';$<HTMLElement>('#engine-dot').classList.remove('ready');
 $<HTMLElement>('#engine-note').textContent='The last displayed ledger is inactive. Restart creates an empty sandbox and keeps your source email. No interrupted action is replayed.';
 $<HTMLElement>('#analysis').innerHTML='<p class="empty">The Python session is unavailable. Your source email is still here. Restart, then analyze it again.</p>';
 status(recoveryMessage(error),'error');
}
function setControls(enabled:boolean){ready=enabled;for(const id of ['fixture-select','load-fixture','job-email','analyze','demo-date','advance-clock','run-chase','reset-sandbox','payment-amount'])$<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>(`#${id}`).disabled=!enabled;}function renderAnalysis(ex:any){
 analysisResult=ex;const panel=$<HTMLElement>('#analysis'),items=ex.line_items||[],issues=ex.issues||[];
 const rows=items.map((x:any)=>`<tr><td>${esc(x.desc)}</td><td>${esc(x.qty??'Unclear')} ${esc(x.unit||'')}</td><td>${esc(x.currency||ex.currency||'')}</td><td>${esc(x.unit_price)}</td></tr>`).join('');
 const flags=issues.length?issues.map((x:any)=>`<li class="issue ${esc(x.severity)}"><b>${esc(String(x.severity).toUpperCase())} / ${esc(x.field)}</b><span>${esc(x.message)}</span></li>`).join(''):'<li class="issue info"><b>NO FLAGS</b><span>The rule validator found no issue.</span></li>';
 panel.innerHTML=`<div class="analysis-head"><div><span class="eyebrow">RULE EXTRACTOR / REAL OUTPUT</span><strong>${Math.round((ex.confidence||0)*100)}% confidence</strong></div><span class="source-chip">${esc(ex.source||'rules')}</span></div><div class="client-row"><span>${esc(ex.client_name||'Client name not found')}</span><span>${esc(ex.client_email||'Recipient email not found')}</span></div><div class="field-row"><span>CURRENCY</span><b>${esc(ex.currency||'Unclear')}</b><span>TERMS</span><b>${ex.due_days?`NET ${esc(ex.due_days)} DAYS`:'NOT FOUND'}</b></div><div class="item-table"><table><thead><tr><th>LINE ITEM</th><th>QTY</th><th>CCY</th><th>UNIT</th></tr></thead><tbody>${rows||'<tr><td colspan="4">No line items recognized.</td></tr>'}</tbody><tfoot><tr><td colspan="3">EXTRACTED TOTAL</td><td>${esc(ex.currency||'')} ${esc(ex.total||'0')}</td></tr></tfoot></table></div><ul class="issue-list">${flags}</ul><p class="fine-print">Errors or confidence below the safety threshold block invoice drafting.</p>`;
 const blocked=issues.some((x:any)=>x.severity==='error')||(ex.confidence||0)<0.5||!items.length;$<HTMLButtonElement>('#draft').disabled=!ready||blocked||busy;
}function renderState(state:any){
 $<HTMLElement>('#mock-requests').textContent=String(state.mock_requests??0);$<HTMLElement>('#external-calls').textContent=String(state.external_calls??0);
 const dateInput=$<HTMLInputElement>('#demo-date');if(document.activeElement!==dateInput)dateInput.value=state.today||'';$<HTMLButtonElement>('#replay-webhook').disabled=!ready||!state.can_replay||busy;
 const queue=state.pending||[];$<HTMLElement>('#approval-list').innerHTML=queue.length?queue.map((a:any)=>`<article class="approval-card"><div class="approval-head"><span class="source-chip">${esc(a.kind==='send_invoice'?'SEND INVOICE':'SEND REMINDER')}</span><span class="mono">${esc(a.invoice_id)}</span></div><p>${esc(a.summary)}</p><div class="button-row"><button class="button button-approve" data-approve="${esc(a.id)}">Approve in sandbox</button><button class="button button-reject" data-reject="${esc(a.id)}">Reject</button></div></article>`).join(''):'<p class="empty">No approvals waiting. Sends and reminders stay queued until you choose.</p>';
 const ledger=state.ledger||[];$<HTMLElement>('#ledger-list').innerHTML=ledger.length?ledger.map((e:any)=>{const open=['SENT','PARTIALLY_PAID','UNPAID'].includes(e.status)&&Number(e.balance)>0;return `<article class="invoice-card" data-due="${esc(e.due_on||'')}"><div class="invoice-head"><div><span class="eyebrow">${esc(e.invoice_number)}</span><h3>${esc(e.client_name||e.client_email||'Client')}</h3></div><span class="status-chip ${esc(String(e.status).toLowerCase())}">${esc(e.status)}</span></div><div class="invoice-meta"><span>${esc(e.currency)} ${esc(e.total)}</span><span>PAID ${esc(e.paid_amount)}</span><span>BALANCE ${esc(e.balance)}</span></div><div class="invoice-meta"><span>DUE ${esc(e.due_on||'Terms missing')}</span><span>REMINDERS ${esc(e.reminders_sent)}</span></div>${open?`<button class="button button-payment" data-pay="${esc(e.invoice_id)}">Simulate sandbox payment</button>`:''}</article>`;}).join(''):'<p class="empty">No invoices in this sandbox ledger yet.</p>';
 const audit=state.audit||[];$<HTMLOListElement>('#audit-list').innerHTML=audit.length?audit.map((e:any)=>`<li><span>${esc(e.event||'event')}</span><code>${esc(e.kind||e.tool||e.invoice||e.action||'')}</code><time>${esc((e.at||'').slice(11,19))}</time></li>`).join(''):'<li class="empty">Agent events will appear here as work runs.</li>';
}async function runAction(name:string,payload:Record<string,unknown>={}){if(!ready&&name!=='init'){status('Load the local Python engine first.','error');return null;}try{const reply=await call(name,payload);if(!reply.ok){status(reply.message||reply.error||'The sandbox action failed.','error');return reply;}renderState(reply.state);if(reply.result?.message)status(reply.result.message,'ready');else if(reply.result?.final)status(reply.result.final,'ready');return reply;}catch(error){status(error instanceof WorkerUnavailableError?recoveryMessage(error):String(error),'error');return null;}}
$('#engine-start').addEventListener('click',async()=>{
 const b=$<HTMLButtonElement>('#engine-start'),restarting=needsFreshSandbox;b.disabled=true;
 status('Loading local Python and Ledgerly source...','loading');const reply=await runAction('init');
 if(reply?.ok){
  needsFreshSandbox=false;setControls(true);b.textContent='Python engine loaded';
  $<HTMLElement>('#engine-status').textContent='PYTHON READY / OFFLINE';$<HTMLElement>('#engine-dot').classList.add('ready');
  $<HTMLElement>('#engine-note').textContent='The sandbox stays in this tab. Close or reset it to discard its ledger.';
  for(const id of ['approval-list','ledger-list'])$<HTMLElement>(`#${id}`).removeAttribute('aria-disabled');
  status(restarting?'New empty sandbox ready. Your source email is preserved; analyze it again.':'Local sandbox ready. No external service is connected.','ready');
 }else{
  b.disabled=false;b.textContent=needsFreshSandbox?'Restart empty sandbox':'Retry loading engine';
  if(!needsFreshSandbox)$<HTMLElement>('#engine-note').textContent='Loading did not finish. Retry loading the engine when the runtime files are available. Your source email is preserved.';
 }
});
$('#load-fixture').addEventListener('click',async()=>{try{const name=$<HTMLSelectElement>('#fixture-select').value;const r=await fetch(new URL(`fixtures/${name}`,new URL('./',window.location.href)));if(!r.ok)throw new Error(`Fixture HTTP ${r.status}`);$<HTMLTextAreaElement>('#job-email').value=await r.text();analysisResult=null;$<HTMLButtonElement>('#draft').disabled=true;status('Fictional input loaded. Analyze it with the real Python rules.','ready');}catch(error){status(String(error),'error');}});
$('#job-email').addEventListener('input',()=>{analysisResult=null;$<HTMLButtonElement>('#draft').disabled=true;});
$('#analyze').addEventListener('click',async()=>{const text=$<HTMLTextAreaElement>('#job-email').value;if(!text.trim()){status('Paste or load a job email first.','error');return;}status('Running RulesExtractor in Python...','loading');const reply=await runAction('analyze',{text});if(reply?.ok){renderAnalysis(reply.result);const bad=reply.result.issues?.some((x:any)=>x.severity==='error')||(reply.result.confidence||0)<0.5||!reply.result.line_items?.length;$<HTMLButtonElement>('#draft').disabled=bad;status(bad?'Review the blocking issue before drafting.':'Review extracted fields, then create the in-memory draft.','ready');}});
$('#draft').addEventListener('click',async()=>{if(!analysisResult)return;$<HTMLButtonElement>('#draft').disabled=true;status('Running Ledgerly Agent + RulePlanner against SandboxMock...','loading');const reply=await runAction('draft',{text:$<HTMLTextAreaElement>('#job-email').value});if(reply?.ok)status(reply.result.unauthorized_send_blocked?'Gate verified: an unapproved send was blocked. '+reply.result.final:reply.result.final,'ready');});$('#approval-list').addEventListener('click',async(event)=>{const b=(event.target as HTMLElement).closest<HTMLButtonElement>('button[data-approve],button[data-reject]');if(!b)return;b.disabled=true;const id=b.dataset.approve||b.dataset.reject||'';const reply=await runAction(b.dataset.approve?'approve':'reject',{action_id:id});if(reply?.ok)status(reply.result.approved?'Approved in the in-memory sandbox. No PayPal request was made.':'Rejected; nothing was sent.','ready');});
$('#ledger-list').addEventListener('click',async(event)=>{const b=(event.target as HTMLElement).closest<HTMLButtonElement>('button[data-pay]');if(!b)return;b.disabled=true;const amount=$<HTMLInputElement>('#payment-amount').value.trim();const reply=await runAction('payment',{invoice_id:b.dataset.pay||'',amount:amount||null});if(reply?.ok)status(`Mock webhook verified: ${reply.result.from} -> ${reply.result.to}.`,'ready');});
$('#advance-clock').addEventListener('click',async()=>{const day=$<HTMLInputElement>('#demo-date').value;if(!day){status('Choose a date for the local clock.','error');return;}await runAction('advance',{day});});
$('#run-chase').addEventListener('click',async()=>{status('Running the overdue scan and reminder rules...','loading');await runAction('chase');});
$('#replay-webhook').addEventListener('click',async()=>{const reply=await runAction('replay');if(reply?.ok)status(reply.result.duplicate?'Duplicate webhook safely ignored by Ledgerly.':'Webhook processed.','ready');});
$('#reset-sandbox').addEventListener('click',async()=>{if(!confirm('Discard the in-memory ledger and clear the pasted email?'))return;const reply=await runAction('reset');if(reply?.ok){analysisResult=null;$<HTMLTextAreaElement>('#job-email').value='';$<HTMLElement>('#analysis').innerHTML='<p class="empty">Sandbox reset. Load a fixture or paste a new email.</p>';$<HTMLButtonElement>('#draft').disabled=true;$<HTMLInputElement>('#payment-amount').value='';status('Sandbox reset. No records were persisted.','ready');}});
